version: 2
updates:
  - package-ecosystem: npm
    directory: /docs
    schedule:
      interval: weekly
    groups:
      documentation-tooling:
        patterns:
          - "mermaid"
          - "vitepress"
          - "vitepress-plugin-mermaid"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
